# Generated by Django 5.1.7 on 2025-03-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soumissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.FloatField()),
                ('feedback', models.TextField()),
                ('date_correction', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soumissions.soumission')),
            ],
        ),
    ]
